const $=id=>document.getElementById(id);const ageEl=$('age'),targetEl=$('targetMonth'),incomeEl=$('income'),careEl=$('careType'),insurerEl=$('insurer'),medicalEl=$('medicalTotal'),copayEl=$('copayTotal'),householdEl=$('householdCopay'),facilitiesEl=$('facilities'),monthsEl=$('months'),resultEl=$('result'),ageNote=$('ageNote'),aggregateNote=$('aggregateNote');
const pad=n=>String(n).padStart(2,'0');const yen=n=>Number.isFinite(n)?Math.round(n).toLocaleString('ja-JP')+'円':'—';
const INCOME={under70:[['A','区分ア：標準報酬月額83万円以上'],['B','区分イ：53～79万円'],['C','区分ウ：28～50万円'],['D','区分エ：26万円以下'],['E','区分オ：住民税非課税']],senior:[['S3','現役並みⅢ：標準報酬月額83万円以上'],['S2','現役並みⅡ：53～79万円'],['S1','現役並みⅠ：28～50万円'],['G2','一般：2割負担（一般Ⅱ）'],['G1','一般：1割負担（一般Ⅰ）'],['L2','低所得Ⅱ（区分Ⅱ）'],['L1','低所得Ⅰ（区分Ⅰ）']]};
function setIncome(){const old=incomeEl.value;incomeEl.innerHTML='';const list=ageEl.value==='under70'?INCOME.under70:INCOME.senior;list.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;incomeEl.appendChild(o)});if([...incomeEl.options].some(o=>o.value===old))incomeEl.value=old;updateNotes()}
function updateNotes(){if(ageEl.value==='under70'){ageNote.textContent='70歳未満は医療機関等ごとの自己負担21,000円以上を原則として世帯合算します。外来・入院の区別による個人上限はありません。';careEl.value='household';careEl.disabled=true}else{careEl.disabled=false;ageNote.textContent=ageEl.value==='70_74'?'70～74歳：外来（個人）上限と外来＋入院（世帯）上限があります。外来限度額だけで該当した月は多数回該当の回数に含めません。':'75歳以上：後期高齢者医療制度の月額上限を表示します。外来（個人）と外来＋入院（世帯）を区別します。'}renderHistory()}
function makeHistoryState(){return JSON.parse(localStorage.getItem('kougakuTasuikaiV2')||'{}')}
function renderHistory(){monthsEl.innerHTML='';const t=targetEl.value?new Date(targetEl.value+'-01'):new Date();const saved=makeHistoryState().history||{};for(let i=12;i>=1;i--){const d=new Date(t.getFullYear(),t.getMonth()-i,1),key=`${d.getFullYear()}-${pad(d.getMonth()+1)}`,wrap=document.createElement('div');wrap.className='historyItem';const title=document.createElement('strong');title.textContent=`${d.getFullYear()}年${d.getMonth()+1}月`;const sel=document.createElement('select');sel.dataset.key=key;const opts=ageEl.value==='under70'?[['0','該当なし'],['1','高額療養費該当']]:[['0','該当なし'],['1','高額療養費該当（世帯）'],['2','外来のみ（非カウント）']];opts.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;sel.appendChild(o)});sel.value=saved[key]||'0';sel.onchange=save;wrap.append(title,sel);monthsEl.appendChild(wrap)}}
function addFacility(name='',amount=''){const row=document.createElement('div');row.className='facility';row.innerHTML=`<input class="fname" placeholder="医療機関・薬局" value="${name.replace(/"/g,'&quot;')}"><input class="famount" type="number" min="0" step="1" inputmode="numeric" placeholder="自己負担円" value="${amount}"><button type="button" aria-label="削除">×</button>`;row.querySelector('button').onclick=()=>{row.remove();updateAggregate();save()};row.querySelectorAll('input').forEach(x=>x.oninput=()=>{updateAggregate();save()});facilitiesEl.appendChild(row)}
function getFacilities(){return [...document.querySelectorAll('.facility')].map(r=>Number(r.querySelector('.famount').value)||0).filter(v=>v>0)}
function updateAggregate(){const vals=getFacilities();if(ageEl.value==='under70'&&vals.length){const eligible=vals.filter(v=>v>=21000).reduce((a,b)=>a+b,0);aggregateNote.textContent=`70歳未満：入力された施設分 ${yen(vals.reduce((a,b)=>a+b,0))} のうち、21,000円以上の ${yen(eligible)} を合算対象として計算します。薬局分は処方元医療機関分との合算を考慮してください。`}else if(vals.length){aggregateNote.textContent=`入力施設分の自己負担合計：${yen(vals.reduce((a,b)=>a+b,0))}` }else aggregateNote.textContent='医療機関ごとの入力がない場合は「自己負担額合計」を使用します。'}
function limitInfo(){const m=Math.max(0,Number(medicalEl.value)||0),a=ageEl.value,i=incomeEl.value,care=careEl.value;let ordinary,majority,annual=null,label='';if(a==='under70'){const d={A:[270300,901000,140100,1680000],B:[179100,597000,93000,1110000],C:[85800,286000,44400,530000],D:[61500,null,44400,530000],E:[36900,null,24600,290000]}[i];ordinary=d[1]===null?d[0]:d[0]+Math.max(0,m-d[1])*.01;majority=d[2];annual=d[3];label=incomeEl.options[incomeEl.selectedIndex].text}else{const d={S3:[270300,901000,140100,1680000],S2:[179100,597000,93000,1110000],S1:[85800,286000,44400,530000],G2:[61500,null,44400,530000],G1:[61500,null,44400,530000],L2:[25700,null,24600,290000],L1:[15700,null,null,180000]}[i];if(care==='outpatient'){const out={G2:22000,G1:22000,L2:11000,L1:8000}[i];ordinary=out??(d[1]===null?d[0]:d[0]+Math.max(0,m-d[1])*.01);majority=null;annual={G2:216000,G1:216000,L2:96000,L1:null}[i]??null}else{ordinary=d[1]===null?d[0]:d[0]+Math.max(0,m-d[1])*.01;majority=d[2];annual=d[3]}label=incomeEl.options[incomeEl.selectedIndex].text}return{ordinary,majority,annual,label}}
function historyCount(){return [...document.querySelectorAll('.historyItem select')].filter(s=>s.value==='1').length}
function save(){const history={};document.querySelectorAll('.historyItem select').forEach(s=>history[s.dataset.key]=s.value);const facilities=[...document.querySelectorAll('.facility')].map(r=>({name:r.querySelector('.fname').value,amount:r.querySelector('.famount').value}));localStorage.setItem('kougakuTasuikaiV2',JSON.stringify({age:ageEl.value,target:targetEl.value,income:incomeEl.value,care:careEl.value,insurer:insurerEl.value,medical:medicalEl.value,copay:copayEl.value,household:householdEl.value,facilities,history}))}
function load(){const s=makeHistoryState(),now=new Date();targetEl.value=s.target||`${now.getFullYear()}-${pad(now.getMonth()+1)}`;ageEl.value=s.age||'under70';setIncome();incomeEl.value=s.income||incomeEl.value;careEl.value=s.care||'household';insurerEl.value=s.insurer||'same';medicalEl.value=s.medical||'';copayEl.value=s.copay||'';householdEl.value=s.household||'';facilitiesEl.innerHTML='';(s.facilities||[]).forEach(f=>addFacility(f.name,f.amount));if(!s.facilities?.length)addFacility();renderHistory();updateAggregate()}
function currentCopay(){const direct=Number(copayEl.value)||0,house=Number(householdEl.value)||0;if(house>0)return house;const vals=getFacilities();if(vals.length){if(ageEl.value==='under70')return vals.filter(v=>v>=21000).reduce((a,b)=>a+b,0);return vals.reduce((a,b)=>a+b,0)}return direct}
function judge(){const info=limitInfo();const copay=currentCopay();const ordinaryHit=copay>=info.ordinary&&info.ordinary>0;const hist=historyCount();const currentCounts=ordinaryHit&&!(ageEl.value!=='under70'&&careEl.value==='outpatient');const same=insurerEl.value==='same';const multi=same&&currentCounts&&hist>=3;const finalLimit=multi&&info.majority?info.majority:info.ordinary;const refund=Math.max(0,copay-finalLimit);let cls=multi?'good':ordinaryHit?'warn':'bad';let title=multi?'今回、多数回該当（4回目以降）の可能性が高い':ordinaryHit?'高額療養費に該当する可能性があります':'今回の自己負担額は月額限度額以下です';let count=hist+(currentCounts&&same?1:0);let notes=[];if(!same)notes.push('保険者または被保険者が変更されているため、過去月をそのまま多数回該当へ通算していません。');if(ageEl.value!=='under70'&&careEl.value==='outpatient')notes.push('外来（個人）だけでの該当月は、多数回該当のカウントには含めません。');if(!Number(medicalEl.value))notes.push('総医療費10割額が未入力のため、定額区分ではない限度額の1%部分を正確に計算できません。');resultEl.className=`result ${cls}`;resultEl.innerHTML=`<h3>${title}</h3><div class="metric"><div>所得区分<b>${info.label}</b></div><div>今回の判定対象額<b>${yen(copay)}</b></div><div>通常の月額限度額<b>${yen(info.ordinary)}</b></div><div>適用後限度額<b>${yen(finalLimit)}</b></div><div>高額療養費見込額<b>${yen(refund)}</b></div><div>多数回該当カウント<b>${count}回 ${multi?'（今回4回目以降）':''}</b></div></div><p>${ordinaryHit?'通常限度額に到達する自己負担額です。':'通常限度額には到達していません。'} ${multi?'多数回該当限度額を適用しています。':''}</p>${info.annual?`<p>年間上限（2026年8月～2027年7月）：<b>${yen(info.annual)}</b> ※年間上限は月額判定とは別に保険者で精算されます。</p>`:''}${notes.map(n=>`<p class="warning">${n}</p>`).join('')}<p class="warning">最終的な多数回該当・世帯合算・年間上限・支給額は加入保険者の審査を優先してください。</p>`;resultEl.classList.remove('hidden');save()}
$('use30').onclick=()=>{const m=Number(medicalEl.value)||0;if(m)copayEl.value=Math.round(m*.3);updateAggregate();save()};$('addFacility').onclick=()=>{addFacility();save()};ageEl.onchange=()=>{setIncome();save()};targetEl.onchange=()=>{renderHistory();save()};incomeEl.onchange=save;careEl.onchange=save;insurerEl.onchange=save;medicalEl.oninput=save;copayEl.oninput=save;householdEl.oninput=save;$('judge').onclick=judge;$('reset').onclick=()=>{if(confirm('入力をすべてリセットしますか？')){localStorage.removeItem('kougakuTasuikaiV2');location.reload()}};load();